[greenclip]
	blacklisted_applications = []
	enable_image_support = true
	history_file = "/home/marco/.cache/greenclip.history"
	image_cache_directory = "/tmp/greenclip"
	max_history_length = 1000
	max_selection_size_bytes = 8192
	static_history = []
	trim_space_from_selection = false
	use_primary_selection_as_input = false
